# Generated by Django 5.0.2 on 2024-04-13 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_sheet', '0003_alter_clinicaldiagnosis_accompanying_pathologies_type_and_more'),
        ('er_card', '0002_internationalclassificationofdiseases_and_more'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedfile',
            name='patient',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='created_doctor',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='curator_doctor',
            new_name='curator',
        ),
        migrations.AddField(
            model_name='user',
            name='passport_attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/passport/% Y/% m/% d/', verbose_name='Passport attachment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Birth date'),
        ),
        migrations.DeleteModel(
            name='AdmissionData',
        ),
        migrations.DeleteModel(
            name='InternationalClassificationOfDiseases',
        ),
        migrations.DeleteModel(
            name='AttachedFile',
        ),
    ]
