# Generated by Django 5.0.2 on 2024-04-14 07:54

import src.management.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_attachedfile_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_attachment',
            field=models.FileField(blank=True, null=True, upload_to=src.management.utils.get_passport_path, verbose_name='Passport attachment'),
        ),
    ]
