# Generated by Django 5.0.2 on 2024-04-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_sheet', '0002_gracescale_and_more'),
        ('er_card', '0002_internationalclassificationofdiseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldiagnosis',
            name='accompanying_pathologies_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accompanying_pathologies', to='er_card.internationalclassificationofdiseases', verbose_name='Accompanying pathologies type'),
        ),
        migrations.AlterField(
            model_name='clinicaldiagnosis',
            name='primary_disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_diagnosis', to='er_card.internationalclassificationofdiseases', verbose_name='Primary disease'),
        ),
        migrations.AddField(
            model_name='clinicaldiagnosis',
            name='grace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ca_sheet.gracescale', verbose_name='GRACE Scale'),
        ),
    ]
