# Generated by Django 5.0.2 on 2024-04-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_sheet', '0003_alter_clinicaldiagnosis_accompanying_pathologies_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondstagedata',
            name='ecg_attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ecg/', verbose_name='ECG attachment'),
        ),
        migrations.AlterField(
            model_name='secondstagedata',
            name='echocg_attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/echocg/', verbose_name='EchoCG attachment'),
        ),
        migrations.AlterField(
            model_name='secondstagedata',
            name='hm_ecg_attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/hm_ecg/', verbose_name='Holter Monitoring ECG attachment'),
        ),
    ]
