# Generated by Django 5.0.2 on 2024-04-13 10:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('er_card', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalClassificationOfDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Diagnosis code')),
                ('title', models.CharField(max_length=150, verbose_name='Diagnosis title')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
            },
        ),
        migrations.RemoveField(
            model_name='attachedfile',
            name='er_card',
        ),
        migrations.CreateModel(
            name='AdmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(blank=True, null=True, verbose_name='Admission date')),
                ('delivery_time', models.DurationField(blank=True, null=True, verbose_name='Delivery time')),
                ('patient_condition', models.CharField(blank=True, choices=[('satisfactory', 'Satisfactory'), ('moderate', 'Moderate severity'), ('severe', 'Severe'), ('extremely_severe', 'Extremely severe')], max_length=30, null=True, verbose_name='Patient condition')),
                ('patient_complaints', models.TextField(blank=True, null=True, verbose_name='Patient complaints')),
                ('heart_stopped', models.BooleanField(default=False, verbose_name='Heart stopped')),
                ('hospitalization_date', models.DateField(verbose_name='Hospitalization date')),
                ('hospitalization_type', models.CharField(choices=[('planned', 'Planned'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], max_length=15, verbose_name='Hospitalization type')),
                ('diagnosed_by', models.CharField(blank=True, choices=[('outpatient_facility', 'Outpatient facility'), ('ambulance_brigade', 'Ambulance brigade'), ('reception_department', 'Reception department'), ('inpatient_facility', 'Inpatient facility')], max_length=50, null=True, verbose_name='Diagnosed by')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('attached_files', models.FileField(upload_to='attached_files/', verbose_name='Attached files')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_data', to='management.patient', verbose_name='Patient')),
                ('preliminary_diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='er_cards', to='er_card.internationalclassificationofdiseases', verbose_name='Preliminary diagnosis')),
            ],
            options={
                'verbose_name': 'Admission data',
                'verbose_name_plural': 'Admission data',
            },
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='admission_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='er_card.admissiondata', verbose_name='Admission data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electronicrehabilitationcard',
            name='admission_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='er_cards', to='er_card.admissiondata', verbose_name='Admission data'),
        ),
    ]
