# Generated by Django 5.0.2 on 2024-04-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('er_card', '0002_internationalclassificationofdiseases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissiondata',
            name='attached_files',
        ),
    ]
