# Generated by Django 5.0.2 on 2024-04-14 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('er_card', '0003_remove_admissiondata_attached_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='attachment',
            field=models.FileField(default=django.utils.timezone.now, max_length=255, upload_to='uploads/admission_data/attachments/', verbose_name='Attachment'),
            preserve_default=False,
        ),
    ]
