# Generated by Django 5.0.2 on 2024-04-14 07:54

import django.db.models.deletion
import src.er_card.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('er_card', '0004_remove_attachedfile_file_attachedfile_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfile',
            name='admission_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='er_card.admissiondata', verbose_name='Admission data'),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='attachment',
            field=models.FileField(max_length=255, upload_to=src.er_card.utils.get_file_path, verbose_name='Attachment'),
        ),
    ]
